### ISSUE TITLE
Cannot tap anywhere in text field when editing profile

### ISSUE THREAD

**Issue by notforrest** [notforrest/PocketChef#39]
When editing profile information, like Username, Full Name, or Email, you have to tap the text to edit that field.

When there isn't text, for example for Full Name, then you have to tap directly where the text box begins (i.e., under F in Full Name), rather than anywhere in the blank field.

_Originally posted by @eddwang in https://github.com/notforrest/PocketPantry/issues/35#issuecomment-2276610055_

**Comment by kaceyna** [comment]
Was not able to reproduce issue consistently @eddwang
